<script lang="ts">
  import { gameSession } from '$lib/stores/gameStore';
  import type { CrewRole, GameState, Officer } from '$lib/domain/types';
  let { game } = $props<{ game: GameState }>();
  const names: Record<CrewRole, string> = { deckhand: '일반 선원', gunner: '포수', navigator: '항해사', marine: '전투원', carpenter: '수리공', medic: '의무병', cook: '조리사' };
  let wages = $derived((Object.values(game.crew.roles) as number[]).reduce((sum: number, count: number) => sum + count, 0) * 3 + game.officers.reduce((sum: number, officer: Officer) => sum + officer.wage, 0));
  function pay(): void { gameSession.updateGame((state) => state.resources.gold < wages ? state : ({ ...state, resources: { ...state.resources, gold: state.resources.gold - wages }, crew: { ...state.crew, unpaidDays: 0, loyalty: Math.min(100, state.crew.loyalty + 6), morale: Math.min(100, state.crew.morale + 4) } }), true); }
  function shares(): void { gameSession.updateGame((state) => state.resources.gold < 180 ? state : ({ ...state, resources: { ...state.resources, gold: state.resources.gold - 180 }, crew: { ...state.crew, morale: Math.min(100, state.crew.morale + 12), loyalty: Math.min(100, state.crew.loyalty + 8) } }), true); }
</script>
<section class="management-screen"><header class="management-header"><div><span class="eyebrow">MUSTER ROLL</span><h1>선원단과 장교</h1><p class="muted">금화보다 충성은 비싸고, 반란은 언제나 더 비쌉니다.</p></div><span class="tag">사기 {Math.round(game.crew.morale)} · 충성 {Math.round(game.crew.loyalty)}</span></header><div class="management-grid"><article class="panel span-7"><div class="panel-title"><div><span class="eyebrow">CREW ROLES</span><h2>보직 현황</h2></div></div><div class="crew-role-grid">{#each (Object.entries(game.crew.roles) as [CrewRole, number][]) as [role, count]}<div class="crew-role"><small class="muted">{names[role]}</small><b>{count}</b><div class="meter"><span style={`--value:${Math.min(100, count * 8)}%`}></span></div></div>{/each}</div></article><article class="panel span-5"><span class="eyebrow">DISCIPLINE</span><h2>급여와 전리품</h2><div class="map-details"><div class="map-row"><span>이번 급여</span><b>{wages} 금화</b></div><div class="map-row"><span>체불 일수</span><b class:danger={game.crew.unpaidDays > 0}>{game.crew.unpaidDays}일</b></div><div class="map-row"><span>피로</span><b>{Math.round(game.crew.fatigue)}%</b></div><div class="map-row"><span>부상자</span><b>{game.crew.wounded}명</b></div></div><button class="btn wide" onclick={pay}>급여 지급</button><button class="btn primary wide" style="margin-top:.5rem" onclick={shares}>전리품 특별 분배 · 180</button></article><article class="panel span-12"><div class="panel-title"><div><span class="eyebrow">OFFICERS</span><h2>장교 명부</h2></div></div>{#each game.officers as officer}<div class="officer-card"><div class="officer-portrait">{officer.name[0]}</div><div><strong>{officer.name}</strong><small class="muted" style="display:block">{officer.role} · {officer.trait}</small></div><div style="text-align:right"><span class="tag">기술 {officer.skill}</span><small class="muted" style="display:block">충성 {officer.loyalty}</small></div></div>{/each}</article></div></section>
