<script lang="ts">
  import { FACTIONS } from '$lib/domain/catalog';
  import { pursuitTier } from '$lib/domain/factions';
  import type { FactionRelation, GameState } from '$lib/domain/types';
  let { game } = $props<{ game: GameState }>();
  let pursuit = $derived(pursuitTier(game.bounty));
  let relations = $derived(Object.values(game.factions) as FactionRelation[]);
</script>
<section class="management-screen"><header class="management-header"><div><span class="eyebrow">INFLUENCE & NOTORIETY</span><h1>세력과 현상금</h1><p class="muted">누군가는 두려워하고, 누군가는 존경하며, 왕관은 모두 기록합니다.</p></div><span class="tag danger">{pursuit.name} · {Math.round(game.bounty)} 금화</span></header><div class="management-grid"><article class="panel span-8"><div class="panel-title"><div><span class="eyebrow">RELATIONS</span><h2>군도의 세력</h2></div></div><div class="list-stack">{#each relations as relation}{@const faction = FACTIONS[relation.factionId]}<div class="list-row" style="grid-template-columns:1fr 2fr"><div><span style={`color:${faction.color}`}>◆</span> <strong>{faction.name}</strong><small class="muted" style="display:block;margin-top:.25rem">{faction.description}</small></div><div class="stat-grid"><div class="mini-stat"><small>우호</small><b>{Math.round(relation.favor)}</b></div><div class="mini-stat"><small>적대</small><b class:danger={relation.hostility > 60}>{Math.round(relation.hostility)}</b></div><div class="mini-stat"><small>공포</small><b>{Math.round(relation.fear)}</b></div><div class="mini-stat"><small>존경</small><b>{Math.round(relation.respect)}</b></div></div></div>{/each}</div></article><article class="panel span-4"><span class="eyebrow">WANTED DEAD OR ALIVE</span><h2>{game.captain.name}</h2><div class="force-number danger">{Math.round(game.bounty).toLocaleString()}</div><p class="muted">열기 {Math.round(game.heat)}% · 해군 순찰 ×{pursuit.patrolMultiplier}</p><div class="meter"><span style={`--value:${game.heat}%;--meter-color:#ac4538`}></span></div><div class="map-details"><div class="map-row"><span>사냥꾼 조우율</span><b>{Math.round(pursuit.hunterChance * 100)}%</b></div><div class="map-row"><span>본거지 탐지</span><b>{Math.round(game.haven.detectionRisk)}%</b></div><div class="map-row"><span>악명</span><b>{game.captain.infamy}</b></div></div><p class="faint" style="font-size:.7rem">은신 부두, 뇌물, 정보상 기록 조작과 장기간 은신으로 현상금을 줄일 수 있습니다.</p></article></div></section>
