<script lang="ts">
  import { FACTIONS, ZONES } from '$lib/domain/catalog';
  import { acceptMission, claimMissionReward } from '$lib/domain/missions';
  import { gameSession } from '$lib/stores/gameStore';
  import type { GameState, Mission } from '$lib/domain/types';
  let { game } = $props<{ game: GameState }>();
  let missions = $derived(game.missions as Mission[]);
  function accept(mission: Mission): void { gameSession.updateGame((state) => acceptMission(state, mission.id), true); }
  function claim(mission: Mission): void { gameSession.updateGame((state) => claimMissionReward(state, mission.id), true); }
</script>
<section class="management-screen"><header class="management-header"><div><span class="eyebrow">CAPTAIN'S LEDGER</span><h1>임무와 소문</h1><p class="muted">고정된 전설과 세력별 절차적 계약이 세계 상태와 함께 변화합니다.</p></div><span class="tag">활성 {missions.filter((item: Mission) => item.status === 'active').length} / 4</span></header><div class="management-grid"><article class="panel span-8"><div class="panel-title"><div><span class="eyebrow">CONTRACTS</span><h2>계약서</h2></div></div><div class="list-stack">{#each missions as mission}<div class="list-row" style="grid-template-columns:1fr auto"><div><span class="eyebrow">{mission.story ? 'STORY' : mission.issuerFactionId ? FACTIONS[mission.issuerFactionId].shortName : mission.type} · {ZONES[mission.zoneId].name} · 위험 {mission.difficulty ?? 1}</span><h3 style="margin:.25rem 0">{mission.title}</h3><p class="muted" style="font-size:.74rem;margin:0">{mission.description}</p><div class="meter" style="margin-top:.6rem"><span style={`--value:${mission.progress / mission.goal * 100}%`}></span></div><small class="faint">진행 {mission.progress} / {mission.goal}{mission.expiresAt && mission.status === 'available' ? ` · 남은 ${Math.max(0, Math.ceil((mission.expiresAt - Date.now()) / 60000))}분` : ''}</small></div><div style="text-align:right"><span class={`tag ${mission.status === 'complete' ? 'success' : ''}`}>{mission.claimed ? '보상 수령' : mission.status}</span><div class="costs" style="justify-content:flex-end;margin:.5rem 0"><span class="cost">명성 +{mission.renownReward}</span>{#each Object.entries(mission.reward) as [id, amount]}{#if amount}<span class="cost">{id} {amount}</span>{/if}{/each}</div>{#if mission.status === 'available'}<button class="btn small" onclick={() => accept(mission)} disabled={missions.filter((item) => item.status === 'active').length >= 4}>수락</button>{:else if mission.status === 'complete' && !mission.claimed}<button class="btn small primary" onclick={() => claim(mission)}>보상 수령</button>{/if}</div></div>{/each}</div></article><article class="panel span-4"><span class="eyebrow">RUMORS</span><h2>오늘의 소문</h2>{#each game.world.recentEvents as event}<p class="muted" style="padding:.7rem;border-left:2px solid var(--brass);background:rgba(0,0,0,.16)">{event}</p>{/each}<p class="faint">정보상 거점을 업그레이드하면 목표 방어력과 희귀 항로가 공개됩니다.</p></article></div></section>
